---
all:
 vars:
   # changes according to requirements
   zone: us-central1-c
   region: us-central1
   project_id: <project_id> #enter you project id
   gcloud_sa_path: ".config/gcloud/tf-admin.json" # Enter path to you service account json file
   gcloud_service_account: "service-account@project-id.iam.gserviceaccount.com"
   credential: "{{lookup('env','HOME') }}/{{gcloud_sa_path}}"
   

   #Cluster information
   cluster_name: "ansible" #Name of the cluster
   initial_node_count: 1   #Number of node for cluster
   disk_size_gb: 50
   disk_type: "pd-ssd"  #disk types 
   machine_type: "e2-medium"  #image types
   master_cidr: "172.25.0.0/28" #master cidr
   gke_cidr: "10.0.0.0/16" #subnet