---
# tasks file for creating network
- name: create vpc
  google.cloud.gcp_compute_network:
    name: network-{{ cluster_name }}
    auto_create_subnetworks: 'false'
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credential }}"
    state: "{{ cluster_state | default('present') }}"
  register: network

- name: Create subnetwork
  google.cloud.gcp_compute_subnetwork:
    name: subnet-{{ cluster_name }}
    region: "{{ region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ gke_cidr }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ credential }}"
    state: "{{ cluster_state | default('present') }}"
  register: subnet